config/routes.rb
Rails.application.routes.draw do
  get 'winners/index'
  get 'winners/new'
  get '/users', to: 'users#index'
  devise_for :users
  root 'home#index'
  resources :teams
  resources :matches
  resources :tournaments
  resources :players
  resources :memberships
  resources :joinrequests
  resources :winners
  resources :results
 # admin routes
 mount RailsAdmin::Engine => "/admin", as: "rails_admin"
 #document routes
 get 'home/document' => 'home#document'
 get 'home/contact' => 'home#contact'
 post 'tournaments/new' => 'tournaments#new'

end

app/models/comments.rb
class Match < ApplicationRecord
    
end
   

app/models/joinrequest.rb
class Joinrequest < ApplicationRecord
    belongs_to :user
    #belongs_to :team
      # Validates user can only send one join request to team
  validates_uniqueness_of :team_id, scope: :user_id
    # Need validation for verifying that you're not already on the team
    validate :you_cannot_request_to_join_your_own_team

    def you_cannot_request_to_join_your_own_team
      if self.user.teams.any? { |team| team.id == team_id }
        errors.add(:team_id, "can't be an ID of a team you currently belong to")
      end
    end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :team
end

app/models/match.rb
class Match < ApplicationRecord
    belongs_to :tournament, optional: true
 
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
   # belongs_to :team
  
    validates_uniqueness_of :team_id, scope: :user_id
end

app/models/notification.rb
# Class notification < ApplicationRecord
# include Noticed: :Model
# belongs_to :recipient, polymorphic: true


app/models/organizer.rb
class Organizer < ApplicationRecord
    belongs_to :user
    belongs_to :tournament
  
    validates_uniqueness_of :user_id, scope: :tournament_id
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :user
    
    

end

app/models/relation.rb
class Relation < ApplicationRecord
    belongs_to :match
    belongs_to :team
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/roundmatch.rb
class Roundmatch < ApplicationRecord
belongs_to :round
belongs_to :match


end

app/models/score.rb
class Score < ApplicationRecord
    has_many :rounds
    
end

app/models/team.rb
class Team < ApplicationRecord
    #validates :name, presence: true
    #has_many :matches, through: :relation , dependent: :destroy
  #belongs_to :tournament
   ## has_many :users
    has_many :relation
    #has_many :join_requests
    #has_many :requesting_members, through: :join_requests, source: :user
  #  has_many :memberships
  #  has_many :members, through: :memberships, source: :user
end

app/models/team1.rb
class Team1 < ApplicationRecord
    
end

app/models/team2.rb
class Team2 < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
    validates :name, presence: true
    #has_many :matches
    has_many :teams
    has_many :organizers
    has_many :matches

    # Below is likely working but connectivity was not fully checked
  # has_many :organizer_users, through: :admins, source: :user
  
  
  
  
  
  
   # def get_all_available_players
        #@players = Player.where('isavailable is true').order('name')
  #  end
      
      #def build_teams(users)
        #Find the players who are playing ordered by their performance points
       # players = get_all_available_players
        
        # team1 = {}
        # team2 = {}
        
        #Assign the players to teams
       # players.each_with_index do |player, i|
        #   if (i % 2) == 0
        #     team1["#{player.id}"] = "1"
        #   else
        #     team2["#{player.id}"] = "2"
        #   end
        # end
        
        #Randomly choose which teams are going to be home and away
       # teams = [team1, team2].sort_by { rand }
        
        #Assign and save players to the home team side
      #  team.player_list = teams[0]
      #  team.save
        
        #Assign and save players to the away team side
      #   team.player_list = teams[1]
      #   team.save
      # end
      # def adjacent(teams)
      #   teams.each_slice(2).to_a
      # end

      # def fold(teams)
      #   top, bottom = teams.each_slice(teams.length / 2).to_a

      #   bottom.reverse!

      #   top.zip(bottom).to_a
      # end

      # def slide(teams)
      #   top, bottom = teams.each_slice(teams.length / 2).to_a

      #   top.zip(bottom).to_a
      # end
      
      # def random(teams)
      #   adjacent(teams.shuffle)
      # end

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role 

  has_many :players
#belongs_to :users

  def assign_default_role
    self.add_role(:player) if self.roles.blank?
  end 
  #has_many :join_requests
  #has_many :requested_teams, through: :join_requests, source: :team


  
 # has_many :organizers
 # has_many :tournaments, through: :organizers
end

app/models/winner.rb
class Winner < ApplicationRecord
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  

  def index
         @players = Player.all
  end
  
def create
  @player =Player.new(player_params)      
     respond_to do |format|
         if @player.save
           flash[:notice] = 'player was successfully created.'
           format.html { redirect_to(@player) }
         else
           format.html { render action: "new" }
         end
        end 
    

       def new
         @player = Player.new
       end
     end
     def show
      begin
        @player = Player.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        player = nil
      end
    end

     def destroy
       @player = Player.find(params[:id])
       if @player.destroy
         flash[:success] = 'player was successfully deleted.'
         redirect_to players_url
       else
         flash[:error] = 'Something went wrong'
         redirect_to players_url
       end
     end
     def new
       @player = Player.new
     end
     def edit   
       @player =Player.find(params[:id])   
     end   
     def update
      respond_to do |format|
        @player =Player.find(params[:id])
        if @player.update(player_params)
          format.html { redirect_to @player, notice: 'player was successfully updated.' }
        else
          format.html { render :edit }
           end
      end
    end
    private
    def player_params   
      params.require(:player).permit(:name, :email, :description)    
    end 
  end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/players/destory.html.erb
<h1>Players#destory</h1>
<p>Find me in app/views/players/destory.html.erb</p>

app/views/players/edit.html.erb
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
      <%= f.label :email%><br>
    <%= f.text_field :email %>
     <%= f.label :description%><br>
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', @player %> 
<%= link_to 'Back', player_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="my-8 text-4xl font-semibold text-gray-700">players</h1>
<div class="w-full px-4 mb-12 xl:w-8/12 xl:mb-0">
<div class="relative flex flex-col w-full min-w-0 mb-6 break-words bg-white rounded shadow-lg">


	<table class="w-full text-left">
		<thead class="flex w-full text-white bg-gray-800">
			<tr class="flex w-full mb-4">
				<th class="w-1/4 p-4">Name</th>
				<th class="w-1/4 p-4">Email</th>
				<th class="w-1/4 p-4">Description</th>
				

			</tr>
		</thead>
    <tbody class="flex flex-col items-center justify-between w-full overflow-y-scroll bg-grey-light" style="height: 50vh;">
    <% @players.each do |player| %>
      <tr class="flex w-full mb-4">
        <td class="w-1/3 px-4 py-3 text-left"><%= player.name%></td>
        <td class="w-1/3 px-4 py-3 text-left"><%= player.email %></td>
        <td class="px-4 py-3 text-left"> <%= player.description %></td>

        <td class="px-4 py-3 text-left"><a class="hover:text-blue-500"><%= link_to 'Show', player %></a></td>
        <td class="px-4 py-3 text-left"><a class="hover:text-blue-500"><%= link_to 'Edit', edit_player_path(player) %></a></td>
        <td class="px-4 py-3 text-left"><a class="hover:text-blue-500"><%= link_to 'Destroy', player_path(:id => player.id), :method => :delete%></a></td>
      </tr>
    </tbody>
    <% end %>
    </table>
  </div>
</div>
  </div>
    </div>

<%= link_to 'New player', new_player_path %>

app/views/players/new.html.erb

<div class="container"> 
<%= form_with model: @player do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </div>
    <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
<div>   
        
      
      <div> 
        <%= link_to 'Back', { controller: 'players', action: 'index'} %>   
        <%= form.submit 'Create player' ,{ controller: 'players', action: 'create'} %>
         </div>
 
<% end %>
</div>

app/views/players/show.html.erb


<p id="notice"><%= notice %></p>
<h1 class="my-8 text-4xl font-semibold text-gray-700">player Name: &nbsp;
<%= @player.name if @player %></h1>
<div class="w-full px-4 mb-12 xl:w-8/12 xl:mb-0">
  <div class="relative flex flex-col w-full min-w-0 mb-6 break-words bg-white rounded shadow-lg">
    <table class="items-center w-full bg-transparent border-collapse">
      <thead>
        <tr>
          <th class="px-6 py-3 text-xs font-semibold text-left text-gray-600 uppercase whitespace-no-wrap align-middle bg-gray-100 border border-l-0 border-r-0 border-gray-200 border-solid">Name</th>
          <th class="px-6 py-3 text-xs font-semibold text-left text-gray-600 uppercase whitespace-no-wrap align-middle bg-gray-100 border border-l-0 border-r-0 border-gray-200 border-solid">Email</th>
          <th class="px-6 py-3 text-xs font-semibold text-left text-gray-600 uppercase whitespace-no-wrap align-middle bg-gray-100 border border-l-0 border-r-0 border-gray-200 border-solid">Description</th>

          <th class="px-6 py-3 text-xs font-semibold text-left text-gray-600 uppercase whitespace-no-wrap align-middle bg-gray-100 border border-l-0 border-r-0 border-gray-200 border-solid", colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td class="p-4 px-6 text-xs text-left whitespace-no-wrap align-middle border-t-0 border-l-0 border-r-0"><%= @player.name if @player%></td>
            <td class="p-4 px-6 text-xs text-left whitespace-no-wrap align-middle border-t-0 border-l-0 border-r-0"><%= @player.email if @player %></td>
            <td class="p-4 px-6 text-xs text-left whitespace-no-wrap align-middle border-t-0 border-l-0 border-r-0"><%= @player.description if @player%></td>

          </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/players/update.html.erb
<h1>Players#update</h1>
<p>Find me in app/views/players/update.html.erb</p>