config/routes.rb
Rails.application.routes.draw do
  get 'winners/index'
  get 'winners/new'
  get '/users', to: 'users#index'
  devise_for :users
  root 'home#index'
  resources :teams
  resources :matches
  resources :tournaments
  resources :players
  resources :memberships
  resources :joinrequests
  resources :winners
  resources :results
 # admin routes
 mount RailsAdmin::Engine => "/admin", as: "rails_admin"
 #document routes
 get 'home/document' => 'home#document'
 get 'home/contact' => 'home#contact'
 post 'tournaments/new' => 'tournaments#new'

end

app/models/comments.rb
class Match < ApplicationRecord
    
end
   

app/models/joinrequest.rb
class Joinrequest < ApplicationRecord
    belongs_to :user
    #belongs_to :team
      # Validates user can only send one join request to team
  validates_uniqueness_of :team_id, scope: :user_id
    # Need validation for verifying that you're not already on the team
    validate :you_cannot_request_to_join_your_own_team

    def you_cannot_request_to_join_your_own_team
      if self.user.teams.any? { |team| team.id == team_id }
        errors.add(:team_id, "can't be an ID of a team you currently belong to")
      end
    end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :team
end

app/models/match.rb
class Match < ApplicationRecord
    belongs_to :tournament, optional: true
 
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
   # belongs_to :team
  
    validates_uniqueness_of :team_id, scope: :user_id
end

app/models/notification.rb
# Class notification < ApplicationRecord
# include Noticed: :Model
# belongs_to :recipient, polymorphic: true


app/models/organizer.rb
class Organizer < ApplicationRecord
    belongs_to :user
    belongs_to :tournament
  
    validates_uniqueness_of :user_id, scope: :tournament_id
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :user
    
    

end

app/models/relation.rb
class Relation < ApplicationRecord
    belongs_to :match
    belongs_to :team
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/roundmatch.rb
class Roundmatch < ApplicationRecord
belongs_to :round
belongs_to :match


end

app/models/score.rb
class Score < ApplicationRecord
    has_many :rounds
    
end

app/models/team.rb
class Team < ApplicationRecord
    #validates :name, presence: true
    #has_many :matches, through: :relation , dependent: :destroy
  #belongs_to :tournament
   ## has_many :users
    has_many :relation
    #has_many :join_requests
    #has_many :requesting_members, through: :join_requests, source: :user
  #  has_many :memberships
  #  has_many :members, through: :memberships, source: :user
end

app/models/team1.rb
class Team1 < ApplicationRecord
    
end

app/models/team2.rb
class Team2 < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
    validates :name, presence: true
    #has_many :matches
    has_many :teams
    has_many :organizers
    has_many :matches

    # Below is likely working but connectivity was not fully checked
  # has_many :organizer_users, through: :admins, source: :user
  
  
  
  
  
  
   # def get_all_available_players
        #@players = Player.where('isavailable is true').order('name')
  #  end
      
      #def build_teams(users)
        #Find the players who are playing ordered by their performance points
       # players = get_all_available_players
        
        # team1 = {}
        # team2 = {}
        
        #Assign the players to teams
       # players.each_with_index do |player, i|
        #   if (i % 2) == 0
        #     team1["#{player.id}"] = "1"
        #   else
        #     team2["#{player.id}"] = "2"
        #   end
        # end
        
        #Randomly choose which teams are going to be home and away
       # teams = [team1, team2].sort_by { rand }
        
        #Assign and save players to the home team side
      #  team.player_list = teams[0]
      #  team.save
        
        #Assign and save players to the away team side
      #   team.player_list = teams[1]
      #   team.save
      # end
      # def adjacent(teams)
      #   teams.each_slice(2).to_a
      # end

      # def fold(teams)
      #   top, bottom = teams.each_slice(teams.length / 2).to_a

      #   bottom.reverse!

      #   top.zip(bottom).to_a
      # end

      # def slide(teams)
      #   top, bottom = teams.each_slice(teams.length / 2).to_a

      #   top.zip(bottom).to_a
      # end
      
      # def random(teams)
      #   adjacent(teams.shuffle)
      # end

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role 

  has_many :players
#belongs_to :users

  def assign_default_role
    self.add_role(:player) if self.roles.blank?
  end 
  #has_many :join_requests
  #has_many :requested_teams, through: :join_requests, source: :team


  
 # has_many :organizers
 # has_many :tournaments, through: :organizers
end

app/models/winner.rb
class Winner < ApplicationRecord
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def show
    begin
      @match = Match.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      match = nil
    end 
    end
  
    

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to @match
    else
      render :new
    end
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])

    if @match.update(match_params)
      redirect_to @match
    else
      render :edit
    end
  end

  def destroy
    @match = Match.find(params[:id])
      @match.destroy

    redirect_to root_path
  end
  
  private
    def match_params
      params.require(:match).permit(:name, :result, :brodcast_link, :start_date, :end_date, :team_one, :team_two, :score_of_team_two, :score_of_team_one)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/matches/edit.html.erb
 <style>
            .sectionformulaire{
                display : flex;
                flex-direction: column;
                width : 500px;
                margin-top: 5%;
                margin-left: auto;
                margin-right: auto;
            }
            .sectionformulaire input{
                margin-bottom: 5%;
                border : 1px solid black;
                padding-top: 5%;
                border-left: none;
                border-right: none;
                border-top: none;
                width : 500px;
            }
           .sectionformulaire input:focus{
               outline-style: none;
               border-bottom : 1px solid rgb(255,179,32);
           }
            .btns{
                display: flex;
                flex-direction: row;
                margin-bottom : 8%;
            }
            .btndroite, .btngauche{
                border : 1px solid rgb(255,179,32);
                background-color: rgb(255,179,32);
                text-decoration: none;
                color: white;
                text-align: center;
                border-radius: 30px;
                width: 200px;
                margin-left: auto;
                margin-right: auto;
                margin-top: 6%;
                padding : 0;
            }
            .btndroite:hover, .btngauche:hover{
                box-shadow : 1px 1px 10px 1px rgb(255,179,32);
            }
        </style>
 <div class="sectionformulaire">
 <%= form_with model: @match do |f| %>
        <input type="text" placeholder="Name" id= <%= f.text_field :name %></br>
        
        <input type="text" placeholder="Brodcast_link" id=<%= f.text_field :brodcast_link %></br>

        <input placeholder="Star_date" id=<%= f.datetime_field :start_date%> </br>

        <input placeholder="End_date" id=<%= f.datetime_field :end_date%> </br>

        <input type="text" placeholder="score of team one" id=<%= f.text_field :team_one %></br>
        
        <input type="text" placeholder="score of team two" id=<%= f.text_field :team_two %>

        <div class="btns">
          <a class="btndroite" <%= link_to 'Back', match_path %> </a>
          <%= f.button 'update' , controller: 'matches', action: 'edit', :class =>"btngauche" %>
        </div>         
 <%end%>       
    </div>

app/views/matches/index.html.erb
 <style>
.sectiontab{
    margin-top : 4%;
    margin-bottom : 2%;
    display : flex;
    flex-direction : column;
}
table{
    width : 1000px;
    border : 1px solid black;
    table-layout : fixed;
    margin-left : auto;
    margin-right : auto;
    
 }
 th {
  border: 1px solid black;
  text-align : center;
  background-color : black;
  color : rgb(255,179,32);
  font-weight : normal;
  font-size : 15px;
  padding-top : 10px;
  padding-bottom : 10px;
}
td{
  border: 1px solid black;
  text-align : center;
  font-weight : normal;
  font-size : 15px;
  padding-top : 6px;
  padding-bottom : 6px;
  
}
.sectiontab .alienbtn{
    background-color : rgb(255,179,32);
    width : 130px;
    text-align : center;
    border : 1px solid rgb(255,179,32); 
    border-radius : 50px;
    color : white;
    font-size : 13px;
    padding-left : 15px;
    padding-right : 15px;
    padding-top : 6px;
    padding-bottom : 6px;
}
.sectiontab .alienbtn:hover{
  box-shadow : 2px 1px 12px 2px rgb(255,179,32);
  
  }

.lien:hover{
  color: rgb(255,179,32);
}
.lienM{
  margin-top : 3%;
  display : flex ;
  flex-direction : row;
  margin-left : 13%;
}
.matchR{
    background-color : rgb(255,179,32);
    width : 150px;
    text-align : center;
    border : 1px solid rgb(255,179,32); 
    border-radius : 50px;
    color : white;
    font-size : 13px;
    margin-left : auto;
    margin-right : 15%;
    padding-left : 15px;
    padding-right : 15px;
    padding-top : 6px;
    padding-bottom : 6px;
}
.matchR:hover{
  box-shadow : 2px 1px 12px 2px rgb(255,179,32);
  
  }
 </style>

 <div class="sectiontab">
 <table>
 <tr>
 <th>Match name</th>
 <th>Broadcast link</th>
 <th>Start date</th>
 <th>End date</th>
 <th>Team one</th>
 <th>Team two</th>
 <th>Action</th>
 </tr>
 <tr>
 <% @matches.each do |match| %>
 <td><%= match.name %></td>
 <td><a href="/home/document">http://watch-streams</a></td>
 <td><%= match.start_date %></td>
 <td><%= match.end_date %></td>
 <td><%= match.team_one %></td>
 <td><%= match.team_two %></td>
 
 <td class="liens">
    <%= link_to 'Show', match , :class => "lien" %>
    <%= link_to 'Edit ', edit_match_path(match) , :class => "lien" %>
    <%= link_to 'Destroy ', match_path(:id => match.id), :method => :delete, :class => "lien" %>
 </td>

 </tr>

 <% end %>
 </table>

 <div class="lienM">
 <a class="alienbtn" <%= link_to 'New match', new_match_path %> </a>
 <a class="matchR" <%= link_to 'Match Result', results_path %> </a></div>
 </div>

 </div>

app/views/matches/new.html.erb
 <style>
            .sectionformulaire{
                display : flex;
                flex-direction: column;
                width : 500px;
                margin-top: 5%;
                margin-left: auto;
                margin-right: auto;
            }
            .sectionformulaire input{
                margin-bottom: 5%;
                border : 1px solid black;
                padding-top: 5%;
                border-left: none;
                border-right: none;
                border-top: none;
                width : 500px;
            }
           .sectionformulaire input:focus{
               outline-style: none;
               border-bottom : 1px solid rgb(255,179,32);
           }
            .btns{
                display: flex;
                flex-direction: row;
                margin-bottom : 8%;
            }
            .btndroite, .btngauche{
                border : 1px solid rgb(255,179,32);
                background-color: rgb(255,179,32);
                text-decoration: none;
                color: white;
                text-align: center;
                border-radius: 30px;
                width: 200px;
                margin-left: auto;
                margin-right: auto;
                margin-top: 6%;
                padding : 0;
            }
            .btndroite:hover, .btngauche:hover{
                box-shadow : 1px 1px 10px 1px rgb(255,179,32);
            }
        </style>
 <div class="sectionformulaire">
<%= form_with model: @match do |f| %>
        <input type="text" placeholder="Name" id= <%= f.text_field :name %></br>
        
        <input type="text" placeholder="Brodcast_link" id=<%= f.text_field :brodcast_link %></br>

        <input placeholder="Star_date" id=<%= f.datetime_field :start_date%> </br>

        <input placeholder="End_date" id=<%= f.datetime_field :end_date%> </br>

        <input type="text" placeholder="team one" id=<%= f.text_field :team_one %></br>
        
        <input type="text" placeholder="team two" id=<%= f.text_field :team_two %>

        <div class="btns">
          <a class="btndroite" <%= link_to 'Back', { controller: 'matches', action: 'index'} %> </a>
          <%= f.button 'Create match' , controller: 'matches', action: 'create', :class =>"btngauche" %>
        </div>         
 <%end%>       
    </div>

app/views/matches/show.html.erb
 <style>
.sectiontab{
    margin-top : 4%;
    margin-bottom : 2%;
    display : flex;
    flex-direction : column;
}
table{
    width : 1000px;
    border : 1px solid black;
    table-layout : fixed;
    margin-left : auto;
    margin-right : auto;
    
 }
 th {
  border: 1px solid black;
  text-align : center;
  background-color : black;
  color : rgb(255,179,32);
  font-weight : normal;
  font-size : 15px;
  padding-top : 10px;
  padding-bottom : 10px;
}
td{
  border: 1px solid black;
  text-align : center;
  font-weight : normal;
  font-size : 15px;
  padding-top : 6px;
  padding-bottom : 6px;
  
}
.sectiontab .alienbtn{
    background-color : rgb(255,179,32);
    width : 130px;
    text-align : center;
    border : 1px solid rgb(255,179,32); 
    border-radius : 50px;
    color : white;
    font-size : 15px;
    margin-left : 13.5%;
    margin-top : 3%;
    padding-left : 15px;
    padding-right : 15px;
    padding-top : 3px;
    padding-bottom : 3px;
}
.sectiontab .alienbtn:hover{
  box-shadow : 2px 1px 12px 2px rgb(255,179,32);
  
  }

.lien:hover{
  color: rgb(255,179,32);
}
.liens{
    
    
}
 </style>

 <div class="sectiontab">
 <table>
 <tr>
 <th>Match name</th>
 <th>Brodcast link</th>
 <th>Start date</th>
 <th>End date</th>
 <th>Team one</th>
 <th>Team two</th>
 </tr>
 <tr>
 <td><%= @match.name if @match %></td>
 <td><%= @match.brodcast_link if @match %></td>
 <td><%= @match.start_date if @match %></td>
 <td><%= @match.end_date if @match%></td>
 <td><%= @match.team_one %></td>
 <td><%= @match.team_two %></td>
 </tr>

 </table>
 <a class="alienbtn" <%= link_to 'Back', matches_path %> </a>
 </div>